fix(lx2160): build cert_create with the lx2162aqds DDR certificates
Since the commit
 7c3e9a0ca ("fix(lx2160a): put cert_create_tbbr.mk in the standard location")
moved the file next to platform.mk, the X.509 DDR FIP of lx2162aqds
could not be built any more:

It fails with:

  make PLAT=lx2162aqds TRUSTED_BOARD_BOOT=1 NXP_TBBR_USE_X509=1 \
       GENERATE_COT=1 CST_DIR=$CST_DIR BOOT_MODE=flexspi_nor \
       DDR_PHY_BIN_PATH=$DDR_PHY fip_ddr

  ../../include/tools_share/tbbr_oid.h:180:10: fatal error: platform_oid.h: No such file or directory
  make: *** [Makefile:1204: .../tools/cert_create/cert_create] Error 2

Change-Id: Ic6b196e043a8c778156b7a7bcb011ebd4f5e60c0
Signed-off-by: Vincent Jardin <vjardin@free.fr>