refactor(io): use check_size_t_overflow
Use the new check_size_t_overflow helper.

On aarch32 platform, and when enabling -Wsign-compare flag, there is a
warning:
drivers/io/io_block.c: In function 'block_open':
include/lib/utils_def.h:215:17: error: comparison of promoted bitwise
 complement of an unsigned value with unsigned [-Werror=sign-compare]
  215 |         ((_u64) > (UINT64_MAX - (_inc)))
      |                 ^
drivers/io/io_block.c:146:13: note: in expansion of macro
 'check_u64_overflow'
  146 |         if (check_u64_overflow((uint64_t)region->offset,
      |             ^~~~~~~~~~~~~~~~~~

Using this helper corrects that.

Change-Id: I018938dfa55f83bc4b2267fbaa25498889a15113
Signed-off-by: Yann Gautier <yann.gautier@st.com>
(cherry picked from commit 789a4950a86c1e37ebb1adb8c51f76d50f1c1ff7)